/**
 * issue: https://github.com/Tribex/prerenderer/pull/24
 */

import fs from 'fs';
import path from 'path';

const packageName = '@prerenderer/prerenderer';
const es6Path = `es6/server`;
const es5Path = `es5-autogenerated/server`;

function hotFixPrerenderer() {
  [es6Path, es5Path].forEach((modulePath) => {
    let filePath;
    try {
      filePath = require.resolve(path.join(packageName, modulePath));
    } catch (e) {
      // tslint:disable-next-line:no-console
      console.warn(`HotFixPrerenderer Warning: ${modulePath} not found!`);
      return;
    }

    const originScript = fs.readFileSync(filePath, 'utf8');

    fs.writeFileSync(filePath, originScript.replace(/\*\.\*/g, '*'), 'utf8');
  });
}

hotFixPrerenderer();
